#!/usr/bin/env python3
"""Step 5: Post the LLM commit log review as a GitHub PR comment."""

import argparse
import os
import sys
from pathlib import Path

import requests

GITHUB_TOKEN = os.environ["GITHUB_TOKEN"]
REPO = os.environ["REPO"]
PR_NUMBER = os.environ["PR_NUMBER"]


def post_comment(body: str) -> None:
    url = f"https://api.github.com/repos/{REPO}/issues/{PR_NUMBER}/comments"
    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github+json",
    }
    resp = requests.post(url, headers=headers, json={"body": body}, timeout=30)
    resp.raise_for_status()


def main() -> None:
    parser = argparse.ArgumentParser(description="Post commit log review comment")
    parser.add_argument("--input", default="review_output.md", help="File containing the review")
    args = parser.parse_args()

    input_path = Path(args.input)
    if not input_path.exists():
        print(f"Review file not found: {input_path}")
        sys.exit(1)

    review = input_path.read_text()

    full_comment = (
        "> This is an automated review generated by the Commit Log Review Bot. "
        "Feedback is AI-generated and may not be perfect — "
        "maintainers will follow up as needed.\n\n"
        + review
    )

    print("Posting review comment...")
    post_comment(full_comment)
    print("Done.")


if __name__ == "__main__":
    main()
